#include "lang.h"
#include <string.h>
#include "lvgl.h"
#include "settings.h"

static const lang_t k_en = {
    .connecting = "connecting to Wi-Fi...",
    .setup_wifi = "tap %s to set up Wi-Fi",
    .locating = "locating...",
    .geo_retry = "geolocation failed, retrying...",
    .no_data = "no data - check connection",
    .status_fmt = "%.24s | %d ac | %d km",
    .waiting_aircraft = "Waiting for aircraft...",
    .route_unknown = "Route unknown",
    .km_to_go_fmt = "%d%%  -  %.0f km to go%s%s",
    .ground = "ground",
    .map_btn = "Map",
    .ring_fmt = "N up  -  ring %d km",
    .st_alt = "ALTITUDE", .st_speed = "SPEED", .st_vrate = "V/RATE",
    .st_dist = "DISTANCE", .st_track = "TRACK", .st_reg = "REG",
    .settings_title = "Settings",
    .wifi_ssid = "Wi-Fi SSID", .password = "Password",
    .auto_location = "Auto location (IP)", .hide_ground = "Hide ground",
    .airline_only = "Airline only",
    .city_search = "City search", .latitude = "Latitude", .longitude = "Longitude",
    .search_radius = "Search radius", .theme_lbl = "Theme",
    .language_lbl = "Language", .save = "Save",
    .ota_unlock = "Allow OTA updates (until restart)",
    .ota_hint = "Applies immediately, the web panel unlocks within seconds.\n"
                "Do not tap Save: a restart locks OTA again. Just close this screen.",
    .dd_networks = "networks", .dd_results = "results",
    .scanning = "(scanning...)", .no_networks = "(no networks)",
    .not_found = "(not found)", .searching = "(searching...)",
    .saved_restarting = "Saved - restarting...",
    .loading_photo = "Loading photo...", .no_photo = "No photo available",
    .look_fmt = LV_SYMBOL_EYE_OPEN " Look %s, %d\xC2\xB0 above horizon",
    .look_short_fmt = LV_SYMBOL_EYE_OPEN " %s %d\xC2\xB0",
    .cpa_fmt = "flyover in ~%d min (%.1f km)",
    .tab_net = "Network", .tab_place = "Location", .tab_filters = "Filters",
    .tab_integr = "Integrations", .tab_system = "System",
    .cpa_lbl = "Flyover alerts (CPA)",
    .amb_idle_lbl = "Map screensaver after (min, 0=off)",
    .night_lbl = "Night mode", .night_from = "From (HH:MM)", .night_to = "To (HH:MM)",
    .lbl_ntfy = "ntfy.sh topic", .lbl_mqtt = "MQTT broker (Home Assistant)",
    .lbl_fa = "FlightAware API key", .lbl_watch = "Watchlist (e.g. SP-LR,RCH,A388)",
    .lbl_webhook = "Webhook URL", .lbl_ladsb = "Local receiver aircraft.json URL",
    .ladsb_use_lbl = "Use local receiver",
    .hint_ntfy = "Push to your phone: install the ntfy app and subscribe to this topic",
    .hint_mqtt = "mqtt://user:pass@host:1883, sensors auto-appear in Home Assistant",
    .hint_fa = "Adds flight numbers (FR4238); free key: flightaware.com/aeroapi",
    .hint_webhook = "POSTs alert JSON to this URL (Node-RED, n8n, Discord bridge)",
    .lbl_webpass = "Web panel password (empty = open)",
    .cat_word = "Cat.",
    .sec_classes = "AIRCRAFT CLASSES",
    .cls_names = { "Airliner", "Light", "Helicopter", "Military", "Other" },
    .sec_layers = "LAYERS AND EXTRA OBJECTS",
    .rain_lbl = "Rain radar (RainViewer)",
    .route_lbl = "Route on list and radar",
    .bright_lbl = "Brightness", .clk12_lbl = "12-hour clock (AM/PM)",
    .brightctl_lbl = "Brightness control (experimental)",
    .map_light_lbl = "Brighter map tiles",
    .retro_map_lbl = "Map on retro radar",
    .airspace_lbl = "Airspace zones (openAIP)",
    .iss_lbl = "ISS on the radar",
    .sonde_lbl = "Weather balloons (SondeHub)",
    .ships_lbl = "Ships (AIS)",
    .taf_lbl = "TAF airport forecast",
    .lbl_oaip = "openAIP API key",
    .hint_oaip = "Free key at openaip.net, needed for airspace zones",
    .lbl_ais = "aisstream.io API key",
    .hint_ais = "Free key at aisstream.io, needed for the ship layer",
    .sec_maptiles = "MAP TILES",
    .lbl_carto = "CARTO basemaps key",
    .hint_carto = "Optional, free at carto.com/basemaps/apikey; blank = OpenStreetMap with the built-in dark style",
    .lbl_tileurl = "Custom tile URL template",
    .hint_tileurl = "Any {z}/{x}/{y} PNG tile server, overrides both",
    .sec_notify = "NOTIFICATIONS", .sec_datasrc = "DATA SOURCES", .sec_smart = "SMART HOME",
    .lm_planes = "Planes", .lm_ships = "Ships", .lm_all = "All",
    .ship_dest = "DESTINATION", .ship_pos = "POSITION",
    .units_lbl = "Units", .units_opts = "Aviation (ft, kt, \u00b0C)\nAviation (ft, kt, \u00b0F)\nMetric (m, km/h, \u00b0C)",
    .metar_lbl = "METAR", .metar_opts = "Raw\nDecoded",
    .follow_lbl = "Auto-cycle through flights",
    .mtr_wind = "wind", .mtr_gust = "gusts", .mtr_calm = "calm",
    .mtr_vis = "vis", .mtr_cavok = "vis >10 km, no clouds",
    .wifi_no_ap = "network not found - 2.4 GHz? in range?",
    .wifi_badpass = "check the password",
    .night_auto_lbl = "Auto (sunset to sunrise)",
    .update_banner = "New version %s - web panel or flasher",
    .amb_style_lbl = "Screensaver style",
    .amb_style_opts = "Sky map\nRetro radar",
    .amb_loading = "loading map...",
    .apr_fmt = "landing %s ~%d min",
    .lbl_fltapt = "Airport only (ICAO/IATA)",
    .lbl_altmin = "Alt from (ft)", .lbl_altmax = "Alt to (ft)",
    .sec_traffic = "TRAFFIC", .sec_watch = "WATCHLIST", .sec_alerts = "FLYOVER ALERTS",
    .sec_look = "APPEARANCE", .sec_screen = "SCREEN",
    .sec_webpanel = "WEB PANEL", .sec_updates = "UPDATES",
    .cpa_scope_opts = "Interesting only\nAll aircraft",
    .apt_mode_opts = "Show only\nHide",
    .arr_fmt = "arrival ~%s local time",
    .hint_ladsb = "Your own dump1090/readsb receiver instead of the internet APIs",
    .avg_word = "avg", .best_word = "best",
    .view_names = { "Details", "Map", "Radar", "Statistics", "Retro radar" },
    .stats_title = "Session statistics",
    .st_hourly = "NEW AIRCRAFT PER HOUR",
    .st_top_airlines = "TOP AIRLINES",
    .st_unique = "AIRCRAFT",
    .st_fastest = "FASTEST", .st_farthest = "FARTHEST", .st_highest = "HIGHEST",
    .wx_clear = "Clear", .wx_partly = "Partly cloudy", .wx_overcast = "Overcast",
    .wx_fog = "Fog", .wx_drizzle = "Drizzle", .wx_rain = "Rain",
    .wx_snow = "Snow", .wx_showers = "Showers", .wx_thunder = "Thunderstorm",
};

static const lang_t k_pl = {
    .connecting = "łączenie z Wi-Fi...",
    .setup_wifi = "dotknij %s aby ustawić Wi-Fi",
    .locating = "ustalanie pozycji...",
    .geo_retry = "geolokalizacja nieudana, ponawiam...",
    .no_data = "brak danych - sprawdź połączenie",
    .status_fmt = "%.24s | %d szt. | %d km",
    .waiting_aircraft = "Czekam na samoloty...",
    .route_unknown = "Trasa nieznana",
    .km_to_go_fmt = "%d%%  -  %.0f km do celu%s%s",
    .ground = "na ziemi",
    .map_btn = "Mapa",
    .ring_fmt = "N u góry  -  pierścień %d km",
    .st_alt = "WYSOKOŚĆ", .st_speed = "PRĘDKOŚĆ", .st_vrate = "WZNOSZENIE",
    .st_dist = "DYSTANS", .st_track = "KURS", .st_reg = "REJ.",
    .settings_title = "Ustawienia",
    .wifi_ssid = "Sieć Wi-Fi", .password = "Hasło",
    .auto_location = "Lokalizacja auto (IP)", .hide_ground = "Ukryj naziemne",
    .airline_only = "Tylko rejsowe",
    .city_search = "Szukaj miasta", .latitude = "Szerokość", .longitude = "Długość",
    .search_radius = "Promień", .theme_lbl = "Motyw",
    .language_lbl = "Język", .save = "Zapisz",
    .ota_unlock = "Zezwól na aktualizacje OTA (do restartu)",
    .ota_hint = "Działa od razu, panel web odblokuje się w kilka sekund.\n"
                "Nie klikaj Zapisz: restart ponownie zablokuje OTA. Zamknij ten ekran.",
    .dd_networks = "sieci", .dd_results = "wyniki",
    .scanning = "(skanowanie...)", .no_networks = "(brak sieci)",
    .not_found = "(nie znaleziono)", .searching = "(szukam...)",
    .saved_restarting = "Zapisano - restart...",
    .loading_photo = "Wczytywanie zdjęcia...", .no_photo = "Brak zdjęcia",
    .look_fmt = LV_SYMBOL_EYE_OPEN " Patrz %s, %d\xC2\xB0 nad horyzontem",
    .look_short_fmt = LV_SYMBOL_EYE_OPEN " %s %d\xC2\xB0",
    .cpa_fmt = "przelot za ~%d min (%.1f km)",
    .tab_net = "Sieć", .tab_place = "Miejsce", .tab_filters = "Filtry",
    .tab_integr = "Integracje", .tab_system = "System",
    .cpa_lbl = "Alerty przelotu (CPA)",
    .amb_idle_lbl = "Wygaszacz z mapą po (min, 0=wył.)",
    .night_lbl = "Tryb nocny", .night_from = "Od (HH:MM)", .night_to = "Do (HH:MM)",
    .lbl_ntfy = "Temat ntfy.sh", .lbl_mqtt = "Broker MQTT (Home Assistant)",
    .lbl_fa = "Klucz FlightAware API", .lbl_watch = "Watchlista (np. SP-LR,RCH,A388)",
    .lbl_webhook = "Adres webhooka", .lbl_ladsb = "URL aircraft.json lokalnego odbiornika",
    .ladsb_use_lbl = "Używaj lokalnego odbiornika",
    .hint_ntfy = "Push na telefon: zainstaluj apkę ntfy i zasubskrybuj ten temat",
    .hint_mqtt = "mqtt://user:hasło@host:1883, encje same pojawią się w Home Assistant",
    .hint_fa = "Dodaje numery rejsów (FR4238); darmowy klucz: flightaware.com/aeroapi",
    .hint_webhook = "Wysyła POST z JSON-em przy każdym alercie (Node-RED, n8n)",
    .lbl_webpass = "Hasło panelu web (puste = brak)",
    .cat_word = "Kat.",
    .sec_classes = "KLASY STATKÓW",
    .cls_names = { "Rejsowe", "Małe", "Śmigłowce", "Wojskowe", "Inne" },
    .sec_layers = "WARSTWY I DODATKOWE OBIEKTY",
    .rain_lbl = "Radar opadów (RainViewer)",
    .route_lbl = "Trasa na liście i radarze",
    .bright_lbl = "Jasność", .clk12_lbl = "Zegar 12-godzinny (AM/PM)",
    .brightctl_lbl = "Sterowanie jasnością (eksperymentalne)",
    .map_light_lbl = "Jaśniejsza mapa",
    .retro_map_lbl = "Mapa na radarze retro",
    .airspace_lbl = "Strefy przestrzeni (openAIP)",
    .iss_lbl = "ISS na radarze",
    .sonde_lbl = "Balony meteo (SondeHub)",
    .ships_lbl = "Statki (AIS)",
    .taf_lbl = "Prognoza lotniskowa TAF",
    .lbl_oaip = "Klucz API openAIP",
    .hint_oaip = "Darmowy klucz na openaip.net, potrzebny do stref przestrzeni",
    .lbl_ais = "Klucz API aisstream.io",
    .hint_ais = "Darmowy klucz na aisstream.io, potrzebny do warstwy statków",
    .sec_maptiles = "KAFELKI MAPY",
    .lbl_carto = "Klucz CARTO basemaps",
    .hint_carto = "Opcjonalny, darmowy na carto.com/basemaps/apikey; puste = OpenStreetMap z wbudowanym ciemnym stylem",
    .lbl_tileurl = "W\u0142asny szablon URL kafelk\u00f3w",
    .hint_tileurl = "Dowolny serwer PNG {z}/{x}/{y}, nadpisuje oba pozosta\u0142e",
    .sec_notify = "POWIADOMIENIA", .sec_datasrc = "ŹRÓDŁA DANYCH", .sec_smart = "SMART HOME",
    .lm_planes = "Samoloty", .lm_ships = "Statki", .lm_all = "Wszystko",
    .ship_dest = "CEL", .ship_pos = "POZYCJA",
    .units_lbl = "Jednostki", .units_opts = "Lotnicze (ft, kt, \u00b0C)\nLotnicze (ft, kt, \u00b0F)\nMetryczne (m, km/h, \u00b0C)",
    .metar_lbl = "METAR", .metar_opts = "Surowy\nOpisowy",
    .follow_lbl = "Auto-przełączanie lotów",
    .mtr_wind = "wiatr", .mtr_gust = "porywy", .mtr_calm = "cisza",
    .mtr_vis = "widz.", .mtr_cavok = "widz. >10 km, bez chmur",
    .wifi_no_ap = "nie widzę sieci - 2,4 GHz? zasięg?",
    .wifi_badpass = "sprawdź hasło",
    .night_auto_lbl = "Auto (od zachodu do wschodu)",
    .update_banner = "Nowa wersja %s - panel www lub flasher",
    .amb_style_lbl = "Styl wygaszacza",
    .amb_style_opts = "Mapa nieba\nRetro radar",
    .amb_loading = "ładuję mapę...",
    .apr_fmt = "lądowanie %s ~%d min",
    .lbl_fltapt = "Tylko lotnisko (ICAO/IATA)",
    .lbl_altmin = "Pułap od (ft)", .lbl_altmax = "Pułap do (ft)",
    .sec_traffic = "RUCH", .sec_watch = "WATCHLISTA", .sec_alerts = "ALERTY PRZELOTÓW",
    .sec_look = "WYGLĄD", .sec_screen = "EKRAN",
    .sec_webpanel = "PANEL WEB", .sec_updates = "AKTUALIZACJE",
    .cpa_scope_opts = "Tylko ciekawe\nWszystkie",
    .apt_mode_opts = "Pokazuj tylko\nUkryj",
    .arr_fmt = "przylot ~%s czasu lokalnego",
    .hint_ladsb = "Własny odbiornik dump1090/readsb zamiast API z internetu",
    .avg_word = "śr.", .best_word = "rekord",
    .view_names = { "Szczegóły", "Mapa", "Radar", "Statystyki", "Retro radar" },
    .stats_title = "Statystyki sesji",
    .st_hourly = "NOWE MASZYNY WG GODZIN",
    .st_top_airlines = "NAJCZĘSTSZE LINIE",
    .st_unique = "MASZYNY",
    .st_fastest = "NAJSZYBSZY", .st_farthest = "NAJDALSZY", .st_highest = "NAJWYŻEJ",
    .wx_clear = "Bezchmurnie", .wx_partly = "Częściowe zachm.", .wx_overcast = "Pochmurno",
    .wx_fog = "Mgła", .wx_drizzle = "Mżawka", .wx_rain = "Deszcz",
    .wx_snow = "Śnieg", .wx_showers = "Przelotne opady", .wx_thunder = "Burza",
};

const lang_t *L(void)
{
    return settings_get()->lang == 1 ? &k_pl : &k_en;
}

const char *lang_weather_desc(int code)
{
    const lang_t *l = L();
    if (code == 0) return l->wx_clear;
    if (code <= 2) return l->wx_partly;
    if (code == 3) return l->wx_overcast;
    if (code == 45 || code == 48) return l->wx_fog;
    if (code >= 51 && code <= 57) return l->wx_drizzle;
    if (code >= 61 && code <= 67) return l->wx_rain;
    if (code >= 71 && code <= 77) return l->wx_snow;
    if (code >= 80 && code <= 82) return l->wx_showers;
    if (code == 85 || code == 86) return l->wx_snow;
    if (code >= 95) return l->wx_thunder;
    return l->wx_overcast;
}

const char *lang_compass(int deg)
{
    static const char *dirs[8] = { "N", "NE", "E", "SE", "S", "SW", "W", "NW" };
    return dirs[((deg % 360) + 382) / 45 % 8];
}

/* METAR weather-group tokens, localized. Order matters: prefixes first. */
const char *lang_metar_wx(const char *code, int lang_pl)
{
    static const struct { const char *c, *en, *pl; } k[] = {
        { "TS", "thunderstorm", "burza" },
        { "SH", "showers", "przelotnie" },
        { "FZ", "freezing", "marznące" },
        { "RA", "rain", "deszcz" },
        { "DZ", "drizzle", "mżawka" },
        { "SN", "snow", "śnieg" },
        { "GR", "hail", "grad" },
        { "GS", "small hail", "krupa" },
        { "FG", "fog", "mgła" },
        { "BR", "mist", "zamglenie" },
        { "HZ", "haze", "opar" },
        { "FU", "smoke", "dym" },
        { "VC", "nearby", "w pobliżu" },
    };
    for (unsigned i = 0; i < sizeof(k) / sizeof(k[0]); i++) {
        if (strncmp(code, k[i].c, 2) == 0) {
            return lang_pl ? k[i].pl : k[i].en;
        }
    }
    return NULL;
}
